# Generated by Django 5.2.1 on 2025-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='announcementimage',
            options={},
        ),
        migrations.RenameField(
            model_name='announcementimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(upload_to='announcements/'),
        ),
    ]
