# Generated by Django 5.2.1 on 2025-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_announcement_region_announcement_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('announcement_accepted', 'Announcement Accepted'), ('announcement_rejected', 'Announcement Rejected'), ('client_approved', 'Client Approved'), ('announcement_completed', 'Announcement Completed'), ('order_in_process', 'Order In Process'), ('order_completed', 'Order Completed'), ('order_rejected', 'Order Rejected')], max_length=50),
        ),
    ]
