# Generated by Django 5.2.1 on 2025-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When processing started', null=True),
        ),
    ]
