# Generated by Django 5.2.1 on 2025-05-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_announcementproduct'),
        ('orders', '0003_order_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='announcement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='application.announcement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
