name: Deploy Django to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd service/
            git pull origin main
            
            # Python virtual muhitni faollashtirish
            source venv/bin/activate
            
            # Kerakli paketlarni o'rnatish
            pip install -r requirements.txt
            
            # Django migratsiyalarni bajarish va statik fayllarni yig'ish
            python manage.py migrate
            python manage.py collectstatic --no-input
            
            # Xizmatlarni qayta ishga tushirish
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF