name: Deploy Django to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e

            SERVICE_DIR="/home/ec2-user/service"

            echo "Navigating to service directory..."
            cd $SERVICE_DIR

            echo "Pulling latest changes from Git..."
            git fetch origin
            git reset --hard origin/main

            echo "Activating virtual environment..."
            source venv/bin/activate

            echo "Installing/upgrading Python dependencies..."
            pip install --upgrade pip
            pip install -r requirements.txt || (pip install psycopg2-binary && pip install -r requirements.txt --no-deps)

            echo "Running migrations..."
            python manage.py migrate

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Restarting Gunicorn..."
            pkill -f gunicorn || echo "No running gunicorn processes"
            nohup gunicorn --bind 0.0.0.0:8000 config.wsgi:application > gunicorn.log 2>&1 &

            echo "Deployment completed successfully!"