name: Deploy Django to Server with Password

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
        
      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          # Parol orqali SSH ulanish
          sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd service/
            git pull origin main
            
            # Python virtual muhitni faollashtirish
            source venv/bin/activate
            
            # Kerakli paketlarni o'rnatish
            pip install -r requirements.txt
            
            # Django migratsiyalarni bajarish va statik fayllarni yig'ish
            python manage.py migrate
            python manage.py collectstatic --no-input
            
            # Xizmatlarni qayta ishga tushirish
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF